# sink database
sinkdb_jdbcurl: "jdbc:mysql://192.168.30.134:9030"
sinkdb_loadurl: "192.168.30.134:8030"
sinkdb_host: "192.168.30.134"
sinkdb_port: "9030"
sinkdb_username: "sailingdw"
sinkdb_password: "sailingdw"
sinkdb_dbname_suffix: "ods_"

# table rule
"output_dir": "output"

# flink env & parameters
flink_pipeline_name_suffix: "cdc-task-"
flink_env_parameters:
  - parallelism.default=2
  - table.dml-sync=false
  - execution.runtime-mode=streaming

# streamx
streamx_cluster_id: 100000
streamx_url: "http://192.168.30.128:10000/"
streamx_username: "admin"
streamx_password: "streamx"

# source database
sourcedb_host: 192.168.30.130
sourcedb_port: 3306
sourcedb_user: flinkcdc
sourcedb_password: flinkcdc
tables:
  - cdcdemo.table1
  - cdcdemo.table2
  - mgr.sys_account